import express from 'express';
import { body, validationResult } from 'express-validator';
import { createClient } from '@supabase/supabase-js';
import { supabaseAdmin } from '../db/supabase.js';

const router = express.Router();

// Public (anon-key) client for signup/login — Supabase Auth handles these directly.
const supabasePublic = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

// POST /api/auth/signup
router.post(
  '/signup',
  [body('email').isEmail(), body('password').isLength({ min: 8 })],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return res.status(400).json({ error: errors.array()[0].msg });

    const { email, password } = req.body;

    const { data, error } = await supabasePublic.auth.signUp({ email, password });
    if (error) return res.status(400).json({ error: error.message });

    // Create the corresponding row in public.users (app-specific fields).
    // app_id is auto-generated by the DB default.
    const { data: userRow, error: insertError } = await supabaseAdmin
      .from('users')
      .insert({ id: data.user.id, email })
      .select('id, email, plan, app_id')
      .single();

    if (insertError) {
      return res.status(500).json({ error: 'Account created but profile setup failed. Contact support.' });
    }

    return res.status(201).json({
      user: userRow,
      session: data.session // null if email confirmation is required
    });
  }
);

// POST /api/auth/login
router.post(
  '/login',
  [body('email').isEmail(), body('password').notEmpty()],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return res.status(400).json({ error: errors.array()[0].msg });

    const { email, password } = req.body;
    const { data, error } = await supabasePublic.auth.signInWithPassword({ email, password });

    if (error) return res.status(401).json({ error: 'Invalid email or password' });

    return res.json({
      session: data.session, // contains access_token (JWT) for subsequent requests
      user: { id: data.user.id, email: data.user.email }
    });
  }
);

// POST /api/auth/logout
// Note: with Supabase, logout is mostly a client-side token discard.
// This endpoint exists for symmetry and to support server-side session invalidation if added later.
router.post('/logout', async (req, res) => {
  return res.json({ message: 'Logged out. Discard your access token client-side.' });
});

export default router;
